services:
  - type: web
    name: sistema-controle-funcionarios
    env: python
    buildCommand: bash build.sh
    startCommand: python -m waitress-serve --port=$PORT core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src 