services:
  - type: web
    name: sistema-controle-funcionarios
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-controle-funcionarios-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PRODUCTION
        value: true
      - key: DEBUG
        value: false

databases:
  - name: sistema-controle-funcionarios-db
    databaseName: sistema_controle_funcionarios
    plan: free 