services:
  - type: web
    name: sistema-controle-funcionarios
    env: python
    region: ohio
    buildCommand: bash build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
    autoDeploy: true

databases:
  - name: sistema_controle_db
    plan: free
    ipAllowList: [] 