services:
  - type: web
    name: sistema-controle-funcionarios
    env: python
    buildCommand: bash build.sh
    startCommand: /opt/render/project/src/.venv/bin/uvicorn core.asgi:application --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings 