services:
  - type: web
    name: sistema-controle-funcionarios
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: sistema_controle_db
          property: connectionString

databases:
  - name: sistema_controle_db
    plan: free 