# Generated by Django 4.2.7 on 2025-01-03 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("cargo", models.CharField(blank=True, max_length=50, null=True)),
                ("dias_ferias_disponiveis", models.IntegerField(default=30)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plantao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("fds", "Fim de Semana"), ("feriado", "Feriado")],
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantoes",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantão",
                "verbose_name_plural": "Plantões",
            },
        ),
        migrations.CreateModel(
            name="Ferias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("dias_utilizados", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("negado", "Negado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ferias",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Férias",
                "verbose_name_plural": "Férias",
            },
        ),
    ]
