# Generated by Django 4.2.7 on 2025-01-03 23:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ferias",
            options={
                "ordering": ["-data_inicio"],
                "verbose_name": "Férias",
                "verbose_name_plural": "Férias",
            },
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={
                "ordering": ["nome"],
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.AlterModelOptions(
            name="plantao",
            options={
                "ordering": ["data"],
                "verbose_name": "Plantão",
                "verbose_name_plural": "Plantões",
            },
        ),
        migrations.RemoveField(
            model_name="ferias",
            name="observacoes",
        ),
        migrations.AddField(
            model_name="ferias",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AddField(
            model_name="ferias",
            name="data_criacao",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="data_fim",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data de Fim"
            ),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="data_inicio",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data de Início"
            ),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="dias_utilizados",
            field=models.IntegerField(verbose_name="Dias Utilizados"),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ferias",
                to="funcionarios.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="status",
            field=models.CharField(
                choices=[
                    ("AGENDADO", "Agendado"),
                    ("EM_ANDAMENTO", "Em Andamento"),
                    ("USUFRUIDO", "Usufruído"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="AGENDADO",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cargo"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="dias_ferias_disponiveis",
            field=models.IntegerField(
                default=30, verbose_name="Dias de Férias Disponíveis"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="matricula",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Matrícula"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="plantao",
            name="data",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="plantao",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantoes",
                to="funcionarios.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AlterField(
            model_name="plantao",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="plantao",
            name="tipo",
            field=models.CharField(
                choices=[("fds", "Fim de Semana"), ("feriado", "Feriado")],
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
    ]
