# Generated by Django 5.1.4 on 2025-01-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "funcionarios",
            "0002_alter_ferias_options_alter_funcionario_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plantao",
            name="folgas_geradas",
            field=models.IntegerField(default=0, verbose_name="Folgas Geradas"),
        ),
        migrations.AddField(
            model_name="plantao",
            name="folgas_restantes",
            field=models.IntegerField(default=0, verbose_name="Folgas Restantes"),
        ),
        migrations.AddField(
            model_name="plantao",
            name="folgas_utilizadas",
            field=models.IntegerField(default=0, verbose_name="Folgas Utilizadas"),
        ),
    ]
