# Generated by Django 5.1.4 on 2025-01-05 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "funcionarios",
            "0003_plantao_folgas_geradas_plantao_folgas_restantes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UsoFolga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da Folga")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "plantao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_folga",
                        to="funcionarios.plantao",
                        verbose_name="Plantão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso de Folga",
                "verbose_name_plural": "Usos de Folgas",
                "ordering": ["-data"],
            },
        ),
    ]
