# Generated by Django 5.1.4 on 2025-01-05 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0004_usofolga"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferias",
            name="data_retorno",
            field=models.DateField(
                blank=True, null=True, verbose_name="Retorno ao Trabalho"
            ),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="data_fim",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Fim das Férias"
            ),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="data_inicio",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Início das Férias"
            ),
        ),
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "descricao",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NACIONAL", "Nacional"),
                            ("ESTADUAL", "Estadual"),
                            ("MUNICIPAL", "Municipal"),
                            ("FACULTATIVO", "Facultativo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "recorrente",
                    models.BooleanField(
                        default=True,
                        help_text="Se marcado, o feriado se repete todos os anos",
                        verbose_name="Recorrente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feriado",
                "verbose_name_plural": "Feriados",
                "ordering": ["data"],
                "unique_together": {("data", "tipo")},
            },
        ),
    ]
