# Generated by Django 5.1.4 on 2025-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0005_ferias_data_retorno_alter_ferias_data_fim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feriado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("NACIONAL", "Nacional"),
                    ("ESTADUAL", "Estadual"),
                    ("MUNICIPAL", "Municipal"),
                    ("FACULTATIVO", "Facultativo"),
                    ("RECESSO", "Recesso"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
