# Generated by Django 4.2.7 on 2025-01-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0008_remove_ferias_data_atualizacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("sabado", "Sábado"),
                    ("domingo", "Domingo"),
                    ("fds", "Fim de Semana Completo"),
                    ("feriado", "Feriado"),
                ],
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "presente",
                    models.BooleanField(default=False, verbose_name="Presente"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funcionarios.funcionario",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença",
                "verbose_name_plural": "Presenças",
                "ordering": ["-data"],
            },
        ),
    ]
