# Generated by Django 4.2.7 on 2025-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0009_alter_plantao_tipo_presenca"),
    ]

    operations = [
        migrations.AddField(
            model_name="presenca",
            name="tipo_trabalho",
            field=models.CharField(
                choices=[
                    ("PRESENCIAL", "Presencial"),
                    ("TELETRABALHO", "Teletrabalho"),
                ],
                default="PRESENCIAL",
                max_length=20,
                verbose_name="Tipo de Trabalho",
            ),
        ),
    ]
