# Generated by Django 4.2.7 on 2025-01-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0010_presenca_tipo_trabalho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "tipo_folga",
                    models.CharField(
                        choices=[
                            ("COMPENSATÓRIA", "Compensatória"),
                            ("LICENÇA", "Licença"),
                        ],
                        default="COMPENSATÓRIA",
                        max_length=20,
                        verbose_name="Tipo de Folga",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funcionarios.funcionario",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folga",
                "verbose_name_plural": "Folgas",
                "ordering": ["-data"],
            },
        ),
    ]
