# Generated by Django 4.2.7 on 2025-01-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0011_folga"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="presenca",
            options={
                "ordering": ["-data"],
                "verbose_name": "Presencial",
                "verbose_name_plural": "Presencial",
            },
        ),
        migrations.AlterUniqueTogether(
            name="feriado",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="data",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="recorrente",
            field=models.BooleanField(
                default=False,
                help_text="Marque se este feriado se repete todos os anos",
                verbose_name="Feriado Recorrente",
            ),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("NACIONAL", "Nacional"),
                    ("ESTADUAL", "Estadual"),
                    ("MUNICIPAL", "Municipal"),
                ],
                default="NACIONAL",
                max_length=20,
            ),
        ),
    ]
