# Generated by Django 4.2.7 on 2025-01-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "funcionarios",
            "0012_alter_presenca_options_alter_feriado_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="folga",
            name="tipo_folga",
            field=models.CharField(
                choices=[("COMPENSATORIA", "Compensatória"), ("LICENCA", "Licença")],
                default="COMPENSATORIA",
                max_length=20,
                verbose_name="Tipo de Folga",
            ),
        ),
    ]
