# Generated by Django 4.2.7 on 2025-01-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0013_alter_folga_tipo_folga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("SERVIDOR", "Servidor"),
                    ("COORDENADOR", "Coordenador"),
                    ("DIRETOR", "Diretor"),
                    ("ADMINISTRADOR", "Administrador"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
