# Generated by Django 4.2.7 on 2025-01-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0002_load_feriados_data"),
        ("funcionarios", "0015_load_feriados_data"),
    ]

    operations = []
